### PR TITLE
added icons to Preheat/Cooldown buttons

### PR DESCRIPTION
**Pull request by raven-worx**
cooldown
preheat

### CODE REVIEW

**Comment by marian42** [comment]
Thanks! Can you take a look at the font? Once it matches with the other buttons, I'll merge this PR.

**Comment by raven-worx** [comment]
The font will be ok i think, since i only added an element in front of the button text. The screenshots are just inaccurate. I only have this issue on my local machine. I tested it on another machine and there it looked like expected. I haven't looked closer into this yet.

But to make sure you can test it by installing my version of the plugin and check on your machine:
https://github.com/raven-worx/octoprint-preheat/archive/button_icons.zip

**Comment by marian42** [comment]
The font issue appears on my machine, looks just like the screenshot.

**Comment by raven-worx** [comment]
Ok, i will check it and let you know.

**Comment by raven-worx** [comment]
ok i fixed it. Please see again.

Although i had to change the text from "Cooldown" to "Cool" since it looked like this:
image

**Comment by marian42** [comment]
Merged! Thanks again and sorry for the late response.

**Pull request merged**
